Unlock VeraCrypt Volumes: fix required GLib version.
Fixup against 85e9ffd6c7085637bfb5fa2f2f2e3164377ad567.

Otherwise, Unlock VeraCrypt Volumes fails to start with:

 Traceback (most recent call last):
   File "/usr/local/bin/unlock-veracrypt-volumes", line 15, in <module>
     from unlock_veracrypt_volumes.volume_manager import VolumeManager
   File "/usr/lib/python3/dist-packages/unlock_veracrypt_volumes/volume_manager.py", line 11, in <module>
     from unlock_veracrypt_volumes.volume_list import ContainerList, DeviceList
   File "/usr/lib/python3/dist-packages/unlock_veracrypt_volumes/volume_list.py", line 8, in <module>
     from unlock_veracrypt_volumes.volume import Volume
   File "/usr/lib/python3/dist-packages/unlock_veracrypt_volumes/volume.py", line 11, in <module>
     gi.require_version('GLib', '3.0')
   File "/usr/lib/python3/dist-packages/gi/__init__.py", line 121, in require_version
     (namespace, loaded_version))
 ValueError: Namespace GLib is already loaded with version 2.0

And regardless, GObject Introspection data for GLib is currently 2.0,
so I'm pretty sure that requiring 3.0 can't work anyway.