onion-grater: fix rate limiting of how often we try to connect to tor
commit 2a94042845a38d250e09d127805611add8a1a6d1 tried to implement this rate
limiting, but the call to time.sleep(1) always raises an exception:

  NameError: name 'time' is not defined