TCA: re-add necessary step_error_adjustment GtkAdjustment object
Without this, TCA never starts:

   gi.repository.GLib.Error: gtk-builder-error-quark: /usr/share/tails/tca/main.ui:622:51 Object with ID step_error_adjustment not found (13).

This object was added in d3c5e7a1a7b351a59fcb0f0bcc1347a8cd188a05
but apparently, some later merge conflict resolution removed it,
likely by mistake since it's still used.