Don't scrub the environment when Firefox executes itself (refs: #15704).
It causes this error:

  ERROR: ld.so: object 'libmozsandbox.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.

… presumably because LD_LIBRARY_PATH is not set due to the "P" profile
transition flag.