Unlock VeraCrypt Volumes: add missing import.
Fixup against 85e9ffd6c7085637bfb5fa2f2f2e3164377ad567.

Otherwise, Unlock VeraCrypt Volumes fails to start with:

 Traceback (most recent call last):
   File "/usr/local/bin/unlock-veracrypt-volumes", line 15, in <module>
     from unlock_veracrypt_volumes.volume_manager import VolumeManager
   File "/usr/lib/python3/dist-packages/unlock_veracrypt_volumes/volume_manager.py", line 11, in <module>
     from unlock_veracrypt_volumes.volume_list import ContainerList, DeviceList
   File "/usr/lib/python3/dist-packages/unlock_veracrypt_volumes/volume_list.py", line 8, in <module>
     from unlock_veracrypt_volumes.volume import Volume
   File "/usr/lib/python3/dist-packages/unlock_veracrypt_volumes/volume.py", line 8, in <module>
     gi.require_version('Gtk', '3.0')
 NameError: name 'gi' is not defined

Spotted by our automated test suite.