Downgrade to aufs4.6 20160620.
To build correctly, the latest version (more specifically: 4e0cf46)
requires a newer aufs support patch in the kernel headers than what we
currently have in jessie-backports.

Just for the record, with linux-headers-4.6.0-0.bpo.1-* (4.6.3-1~bpo8+1)
the failure is:

 /usr/src/aufs4-standalone/fs/aufs/vfsub.h:223:2: error: implicit
 declaration of function 'update_time' [-Werror=implicit-function-declaration]